### ISSUE TITLE
Websocket模块

### ISSUE THREAD

**Issue by Domineer-Long** [sgtcloud/sgtcloud-node#1]
实现Websocket模块
1、app的jar包中可以自定义Websocket（标准的ServerEndPoint模式或者spring提供的模式）
2、启动时要自动注册
3、重启或者卸载jar包时要能够移除Websocket实例

**Comment by highkay** [comment]
有如下的方案，netty+socket.io的https://github.com/mrniko/netty-socketio 和基于一个抽象框架的Atmosphere（http://async-io.org/） ，前者简单一些，有些成功案例；后者功能强大，复杂度高，更新也比较活跃，有netty的实现http://atmosphere.github.io/nettosphere/ ，还有专门的socket.io实现指南https://github.com/Atmosphere/atmosphere/wiki/Getting-Started-with-Socket.IO  ；最后还有基于tomcat的纯websocket方案。

**Comment by Domineer-Long** [comment]
最终选择netty+socket.io
这个组合比较活跃，netty框架很成熟，但操作比较复杂，结合socketio就变的简单易用，而且对现有大厅游戏模式封装的比较好，自带命名空间和房间概念
大厅游戏现在常见的有两种模式
1、大厅+固定room，房间是运营人员在后台配置好，玩家不能自己创建，如：QQ斗地主
2、大厅+自动room，房间由玩家自己创建，这种模式的游戏比较多，大部分竞技游戏如：CF、炫舞...以及很多卡牌游戏三国杀

不管哪种模式，大厅是固定死的

不足的地方 是netty+socket.io没有官方支持，而且网上现有资料太少

**Comment by Domineer-Long** [comment]
编码部分已经完成
[详见文档](https://github.com/sgtcloud/sgtcloud-node/blob/master/%E4%BA%A7%E5%93%81%E8%AE%BE%E8%AE%A1%E6%96%87%E6%A1%A3/socket%E6%94%AF%E6%8C%81.md)
